# Generated by Django 3.0.3 on 2020-08-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagescans', '0004_imagescans_analyzed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagescans',
            name='user_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
